#cloud-config

package_update: true

packages:
  - mariadb-server
  - wget

runcmd:
  - sed -i "s/.*bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/mariadb.conf.d/50-server.cnf
  - wget -O /tmp/db.sql https://github.com/Ilyas-Nassiri/my_oumma/blob/main/database/my_oumma_emails.sql
  - mysql < /tmp/db.sql
  - systemctl restart mariadb  
  - systemctl enable mariadb

final_message: "The system is finally up, after $UPTIME seconds" 